{"uuid": "0a5dfdd8-3ab4-4de1-b87f-ae99889f00cd", "children": ["5ef1fccf-f2ac-48f4-9744-fed748623789", "f3e54579-f95e-44d2-b973-fa20e2222f97"], "befores": [{"name": "app", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка локатор поля ввода '//*[@id=\"username\"]' - не найден\n", "trace": "  File \"C:\\Users\\gorelov\\git)hub\\web\\WEB\\env\\Lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\gorelov\\git)hub\\web\\WEB\\env\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\gorelov\\git)hub\\web\\WEB\\env\\Lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\gorelov\\git)hub\\web\\WEB\\conftest.py\", line 53, in app\n    fixture.session.ensure_login_remote(username=logAndPas[\"username\"], password=logAndPas[\"password\"])\n  File \"C:\\Users\\gorelov\\git)hub\\web\\WEB\\fixture\\session.py\", line 103, in ensure_login_remote\n    self.login_remote(username, password)\n  File \"C:\\Users\\gorelov\\git)hub\\web\\WEB\\fixture\\session.py\", line 61, in login_remote\n    self.app.method.inputValues(username, '//*[@id=\"username\"]')\n  File \"C:\\Users\\gorelov\\git)hub\\web\\WEB\\fixture\\method.py\", line 42, in inputValues\n    assert e == TimeoutException, f\"Ошибка локатор поля ввода '{locator}' - не найден\"\n           ^^^^^^^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "Авторизация пользователя", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка локатор поля ввода '//*[@id=\"username\"]' - не найден\n", "trace": "  File \"C:\\Users\\gorelov\\git)hub\\web\\WEB\\fixture\\session.py\", line 61, in login_remote\n    self.app.method.inputValues(username, '//*[@id=\"username\"]')\n  File \"C:\\Users\\gorelov\\git)hub\\web\\WEB\\fixture\\method.py\", line 42, in inputValues\n    assert e == TimeoutException, f\"Ошибка локатор поля ввода '{locator}' - не найден\"\n           ^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1671538317842, "stop": 1671538340726}], "start": 1671538317837, "stop": 1671538340727}, {"name": "app", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка! Нет возможности кликнуть по локатору: '('xpath', '//*[@id=\"app\"]//button[.=\" Перейти \"]')'\n", "trace": "  File \"C:\\Users\\gorelov\\git)hub\\web\\WEB\\env\\Lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\gorelov\\git)hub\\web\\WEB\\env\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\gorelov\\git)hub\\web\\WEB\\env\\Lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\gorelov\\git)hub\\web\\WEB\\conftest.py\", line 53, in app\n    fixture.session.ensure_login_remote(username=logAndPas[\"username\"], password=logAndPas[\"password\"])\n  File \"C:\\Users\\gorelov\\git)hub\\web\\WEB\\fixture\\session.py\", line 103, in ensure_login_remote\n    self.login_remote(username, password)\n  File \"C:\\Users\\gorelov\\git)hub\\web\\WEB\\fixture\\session.py\", line 57, in login_remote\n    self.app.method.click((By.XPATH, '//*[@id=\"app\"]//button[.=\" Перейти \"]'))\n  File \"C:\\Users\\gorelov\\git)hub\\web\\WEB\\fixture\\method.py\", line 116, in click\n    assert e == TimeoutException, f\"Ошибка! Нет возможности кликнуть по локатору: '{locator}'\"\n           ^^^^^^^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "Авторизация пользователя", "status": "failed", "statusDetails": {"message": "AssertionError: Ошибка! Нет возможности кликнуть по локатору: '('xpath', '//*[@id=\"app\"]//button[.=\" Перейти \"]')'\n", "trace": "  File \"C:\\Users\\gorelov\\git)hub\\web\\WEB\\fixture\\session.py\", line 57, in login_remote\n    self.app.method.click((By.XPATH, '//*[@id=\"app\"]//button[.=\" Перейти \"]'))\n  File \"C:\\Users\\gorelov\\git)hub\\web\\WEB\\fixture\\method.py\", line 116, in click\n    assert e == TimeoutException, f\"Ошибка! Нет возможности кликнуть по локатору: '{locator}'\"\n           ^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1671538340942, "stop": 1671538341688}], "start": 1671538340937, "stop": 1671538341690}], "start": 1671538340937, "stop": 1671538341803}